"""add stocks table

Revision ID: e462e4622f98
Revises: 
Create Date: 2024-12-31 13:25:25.123086

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy import Table, MetaData, inspect


# revision identifiers, used by Alembic.
revision = 'e462e4622f98'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    meta = MetaData()
    engine = op.get_bind()
    inspector = inspect(engine)

    if 'stocks' not in inspector.get_table_names():
        op.create_table('stocks',
            sa.Column('id', sa.Integer(), nullable=False),
            sa.Column('stock_symbol', sa.String(), nullable=True),
            sa.Column('number_of_shares', sa.Integer(), nullable=True),
            sa.Column('purchase_price', sa.Integer(), nullable=True),
            sa.PrimaryKeyConstraint('id', name=op.f('pk_stocks'))
        )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('stocks')
    # ### end Alembic commands ###
